### ISSUE TITLE
Release notes/changelog?

### ISSUE THREAD

**Issue by badsyntax** [microsoft/folio#229] opened 2021-04-20 12:13 UTC
Hello. I could be missing something but where can I can changelog/release notes? Thanks in advance.

**Comment by mxschmitt** [comment] 2021-05-07 21:10
The package is in preview, so change-logs are not yet provided.

Duplicate of https://github.com/microsoft/playwright-test/issues/249#issuecomment-823335327

**Closed by mxschmitt** 2021-05-07 21:10 UTC
