### ISSUE TITLE
Ignore scanning in node_modules if gitignore is not available

### ISSUE THREAD

**Issue by arjunattam** [microsoft/folio#127] opened 2020-10-26 20:55 UTC
Upgrading to 0.151.1 seems to be broken for me. Tried reinstalling node_modules, but with no luck

```json
  "devDependencies": {
    "@playwright/test": "^0.151.1"
  }
```

```
$ npx folio

Error while reading /Users/arjun/try-runner/node_modules/fd-slicer/test/test.js:
Cannot find module 'stream-equal'
Require stack:
- /Users/arjun/try-runner/node_modules/fd-slicer/test/test.js
- /Users/arjun/try-runner/node_modules/folio/out/runner.js
- /Users/arjun/try-runner/node_modules/folio/out/cli.js
- /Users/arjun/try-runner/node_modules/folio/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/arjun/try-runner/node_modules/fd-slicer/test/test.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Runner.loadFiles (/Users/arjun/try-runner/node_modules/folio/out/runner.js:50:17)
    at runTests (/Users/arjun/try-runner/node_modules/folio/out/cli.js:108:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/arjun/try-runner/node_modules/fd-slicer/test/test.js',
    '/Users/arjun/try-runner/node_modules/folio/out/runner.js',
    '/Users/arjun/try-runner/node_modules/folio/out/cli.js',
    '/Users/arjun/try-runner/node_modules/folio/cli.js'
  ]
}
```

**Comment by mxschmitt** [comment] 2020-10-26 22:19
I experienced the same issue was also not sure if its was because of me. Had a project with only the pw test runner.

**Comment by mxschmitt** [comment] 2020-10-26 22:21
Seems to be a duplicate of #126? We can also close mine one since yours is more detailed.

**Closed** 2020-10-28 22:07 UTC
